# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 176368e3f49893fc32d3e89790191ed9922af5e5a46a00bde8013c021270144f5c5adcaa1fcf1330bf1a5f1ebe6bb3704230bc02f53d2c4ecefdb73a35181539

test:
  secret_key_base: b7213c3b2e33bc58481b3af2da46ce0385ce6dd563a0a7baa2d9b7a98d636c05ac2ee7aec51c645e1f2e1f830b935b24298a1242f1193697f0d0dff2604c409a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
